[project]
name = "jarbis"
version = "0.1.0"
description = "Just A Really Brilliant Intelligent System"
readme = "README.md"
authors = [
    { name = "Massetti Matteo", email = "matteomassetti8@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gitingest>=0.3.1",
    "ollama>=0.6.1",
    "requests>=2.32.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
